version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: noshdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123456
    volumes:
      - nosh_db:/var/lib/postgres/data
volumes:
  nosh_db:
  rabbitmqdata: