# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: noshnow.be
services:
- name: rabbitmq
  image: rabbitmq:management
  bindings:
  - port: 5672
    containerPort: 5672
    protocol: http
  - port: 15672
    containerPort: 15672
    protocol: http
- name: db
  image: postgres
  bindings:
  - port: 5432
    containerPort: 5432
    protocol: http
  env:
  - name: POSTGRES_DB
    value: noshdb
  - name: POSTGRES_USER
    value: myuser
  - name: POSTGRES_PASSWORD
    value: 123456
